name: OSV-Scanner PR Scan

on:
    pull_request:
        branches: [master, dev]
    merge_group:
        branches: [master, dev]

permissions:
    contents: read

jobs:
    scan-pr:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: https://git.quad4.io/actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

            - name: OSV scan
              run: bash scripts/osv_scan.sh
