-keep class com.chaquo.python.** { *; }
-keep class com.meshchatx.** { *; }
-keep class org.json.** { *; }
-keep class org.conscrypt.** { *; }
-dontwarn com.chaquo.python.**
-dontwarn org.conscrypt.**
